### ISSUE TITLE
undefined method `parent_ids' for nil:NilClass

### ISSUE THREAD

**Issue by adpande** [benedikt/mongoid-tree#36]
Using mongoid (3.0.9) 
# Using mongoid-tree (1.0.1) 

Rails Method is throwing  

 def rebuild_path

```
MassTopic.all.each do |topic|
  puts "Buliding Path: " + topic.name
  topic.path = topic.ancestors_and_self.collect{ |item| "#{item.name}||#{item.id}"}.join("$$")

  topic.save

end
respond_to do |format|
  format.html { render :text => "Done"}
end
```

  end
# 

[2012-11-05 21:28:24] ERROR NoMethodError: undefined method `parent_ids' for nil:NilClass
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-tree-1.0.1/lib/mongoid/tree.rb:420:in`rearrange'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-tree-1.0.1/lib/mongoid/tree.rb:95:in `block (3 levels) in <module:Tree>'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:403:in`_run__2708834019810802991__rearrange__21207758887223718__callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `__run_callback'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in`_run_rearrange_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/callbacks.rb:114:in`run_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-tree-1.0.1/lib/mongoid/tree.rb:95:in `block (2 levels) in <module:Tree>'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:407:in`_run__2708834019810802991__validation__21207758887223718__callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `__run_callback'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in`_run_validation_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/callbacks.rb:114:in`run_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activemodel-3.2.8/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activemodel-3.2.8/lib/active_model/validations.rb:194:in`valid?'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/validations.rb:78:in `valid?'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activemodel-3.2.8/lib/active_model/validations.rb:202:in`invalid?'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/persistence/modification.rb:22:in `prepare'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/persistence/operations/update.rb:43:in`persist'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/persistence.rb:139:in `update'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/persistence.rb:81:in`save'
    /home/ec2-user/apps/testtree/app/controllers/homes_controller.rb:48:in `block in rebuild_path'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/contextual/mongo.rb:644:in`yield_document'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/contextual/mongo.rb:134:in `block (2 levels) in each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/moped-1.2.7/lib/moped/query.rb:78:in`block in each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/moped-1.2.7/lib/moped/cursor.rb:26:in `block in each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/moped-1.2.7/lib/moped/cursor.rb:26:in`each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/moped-1.2.7/lib/moped/cursor.rb:26:in `each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/moped-1.2.7/lib/moped/query.rb:77:in`each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/moped-1.2.7/lib/moped/query.rb:77:in `each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/contextual/mongo.rb:133:in`block in each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/contextual/mongo.rb:603:in `selecting'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/contextual/mongo.rb:132:in`each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/contextual.rb:18:in `each'
    /home/ec2-user/apps/testtree/app/controllers/homes_controller.rb:37:in`rebuild_path'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/base.rb:167:in`process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:414:in `_run__1342489903615171212__process_action__184040716227805675__callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in`__run_callback'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in`run_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/callbacks.rb:17:in `process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/rescue.rb:29:in`process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in`block in instrument'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in`instrument'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/base.rb:121:in `process'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/rendering.rb:45:in`process'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal.rb:203:in `dispatch'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal.rb:246:in `block in action'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:73:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:36:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:56:in`each'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:600:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/rack/mongoid/middleware/identity_map.rb:33:in `block in call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/mongoid/unit_of_work.rb:39:in`unit_of_work'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/mongoid-3.0.9/lib/rack/mongoid/middleware/identity_map.rb:33:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/sass-3.2.1/lib/sass/plugin/rack.rb:54:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/etag.rb:23:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/head.rb:14:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/flash.rb:242:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/cookies.rb:339:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `_run__1883085759501563229__call__21207758887223718__callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in`__run_callback'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in`run_callbacks'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/rack/logger.rb:26:in `call_app'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/rack/logger.rb:16:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/request_id.rb:22:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/static.rb:62:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/engine.rb:479:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/application.rb:223:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/rack/log_tailer.rb:17:in`call'
    /home/ec2-user/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
    /home/ec2-user/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
    /home/ec2-user/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
    /home/ec2-user/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

**Comment by macbury** [comment]
+1

**Comment by benedikt** [comment]
@macbury Can you please share a few details about your problem? Usually this happens when there is a node missing, but it is still referenced by another node.

**Comment by prcongithub** [comment]
Is this still unresolved?

**Comment by benedikt** [comment]
@prcongithub This is most likely a problem with the data and not a problem with the code. Can you share more details of your particular case?

**Comment by neongrau** [comment]
Saw this error too and had to patch it by overriding `rearrange`.
Couldn't implement a normal validation because of current handling.

Problem is i'm getting a non-existing parent_id and the `rearrange` method only checks if a parent_id is set, then just calls `parent_parent_ids`.

My local fix:

```ruby
  def rearrange
    if parent.nil? && parent_id.present?
      self.parent_id = nil
      errors.add(:parent_id, :invalid)
    end
    super
  end
```
