### ISSUE TITLE
Missing v2.1.1 readme update (requirements)

### ISSUE THREAD

**Issue by janis-vitols** [benedikt/mongoid-tree#70]
Hi,

Sorry for not creating PR:

* There was 7.0.0 `mongoid` support PR: https://github.com/benedikt/mongoid-tree/pull/69 
* Which now requires `mongoid < 8, >= 4.0` https://rubygems.org/gems/mongoid-tree/versions/2.1.1
* **But** https://github.com/benedikt/mongoid-tree/tree/v2.1.1 still has old information `mongoid (>= 4.0, < 7.0)` in `README.md`

**Comment by benedikt** [comment]
Thanks for bringing this up. The readme is now updated 😃
