### ISSUE TITLE
Compatibility naming

### ISSUE THREAD

**Issue by ekampp** [benedikt/mongoid-tree#73]
Hi, @benedikt.

Is there a way to name the relationships something else than `parent` and `children`? Being able to name them something else would greatly ease the migration process, since my existing project names these relationships something very specific (business domain reasons).

**Comment by benedikt** [comment]
@ekampp There's no official way to do this. You might be able to add aliases, but I don't have a good grasp on how well that'll work.

**Comment by ekampp** [comment]
I tried with aliases, but I'm running into some problems with `BSON::Hash#to_bson`, which raises a `BSON::Error::UnserializableClass` exception. Is that something that you have seen before?

**Comment by benedikt** [comment]
Unfortunately, I haven't seen into this issue before. Sorry!

**Comment by ekampp** [comment]
For posterity: I could not make aliasing work. If/when I get this gem implemented, I will probably make a PR to make this configurable to help others in the future.
